# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[mgr]
cwd = { fg = "#73daca" }

# TODO: remove
# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#e0af68", bold = true, italic = true, underline = true }
find_position = { fg = "#bb9af7", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#41a6b5", bg = "#41a6b5" }
marker_cut      = { fg = "#f7768e", bg = "#f7768e" }
marker_marked   = { fg = "#73daca", bg = "#73daca" }
marker_selected = { fg = "#e0af68", bg = "#e0af68" }

# Count
count_copied   = { fg = "#24283b", bg = "#41a6b5" }
count_cut      = { fg = "#24283b", bg = "#f7768e" }
count_selected = { fg = "#24283b", bg = "#e0af68" }

# Border
border_symbol = "│"
border_style  = { fg = "#414868" }

# : }}}


# : Tabs {{{

[tabs]
active   = { fg = "#c0caf5", bg = "#1f2335", bold = true }
inactive = { fg = "#545c7e", bg = "#1f2335" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#24283b", bg = "#7aa2f7", bold = true }
normal_alt  = { fg = "#7aa2f7", bg = "#414868" }

# Select mode
select_main = { fg = "#24283b", bg = "#73daca", bold = true }
select_alt  = { fg = "#73daca", bg = "#414868" }

# Unset mode
unset_main = { fg = "#24283b", bg = "#ff9e64", bold = true }
unset_alt  = { fg = "#ff9e64", bg = "#414868" }

# : }}}


# : Indicator of hovered file {{{

[indicator]
parent  = { reversed = true }
current = { reversed = true }
preview = { underline = true }
padding = { open = "█", close = "█" }

# : }}}


# : Status bar {{{

[status]
# Permissions
perm_sep   = { fg = "#737aa2" }
perm_type  = { fg = "#7aa2f7" }
perm_read  = { fg = "#e0af68" }
perm_write = { fg = "#f7768e" }
perm_exec  = { fg = "#41a6b5" }

# Progress
progress_label  = { fg = "#c0caf5", bold = true }
progress_normal = { fg = "#41a6b5", bg = "#545c7e" }
progress_error  = { fg = "#e0af68", bg = "#f7768e" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#7aa2f7" }
active   = { fg = "#bb9af7", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#7aa2f7" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Completion {{{

[cmp]
border = { fg = "#7aa2f7" }

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#7aa2f7" }
title   = {}
hovered = { fg = "#bb9af7", bold = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#1f2335" }
cand            = { fg = "#73daca" }
rest            = { fg = "#545c7e" }
desc            = { fg = "#bb9af7" }
separator       = "  "
separator_style = { fg = "#414868" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#73daca" }
run     = { fg = "#bb9af7" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#414868", bg = "#c0caf5" }

# : }}}


# : Spotter {{{

[spot]
border   = { fg = "#7aa2f7" }
title    = { fg = "#7aa2f7" }
tbl_col  = { fg = "#73daca" }
tbl_cell = { fg = "#bb9af7", bg = "#545c7e" }

# : }}}


# : Notification {{{

[notify]
title_info  = { fg = "#41a6b5" }
title_warn  = { fg = "#e0af68" }
title_error = { fg = "#f7768e" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Image
	{ mime = "image/*", fg = "#73daca" },
	# Media
	{ mime = "{audio,video}/*", fg = "#e0af68" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#bb9af7" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#41a6b5" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#545c7e" },
	# Fallback
	{ url = "*", fg = "#c0caf5" },
	{ url = "*/", fg = "#7aa2f7" },
	# TODO: remove
	{ name = "*", fg = "#c0caf5" },
	{ name = "*/", fg = "#7aa2f7" }
]

# : }}}
