add_newline = true
format = """$directory$git_branch$git_metrics$git_status$line_break$character"""
right_format = """$time"""

[directory]
truncation_length = 6
truncation_symbol = "…/"
truncate_to_repo = false

[time]
disabled = false
format = '[$time](fg:8)'

[git_metrics]
disabled = false

[git_branch]
symbol = " "

[package]
disabled = true
