"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = '$hostname$directory$git_branch$fill$time$line_break$character'

[hostname]
ssh_only = false
ssh_symbol = ' '
format = '[$ssh_symbol](fg:1)[$hostname](fg:8) '
trim_at = '.'
disabled = false

[directory]
truncation_length = 5
truncate_to_repo = false
style = 'fg:4'

[git_branch]
symbol = '󰘬 '
style = 'fg:8'
format = '[$symbol$branch(:$remote_branch)]($style) '
ignore_branches = []

[character]
success_symbol = '[󰁕](fg:4)'
error_symbol = '[󰁕](fg:1)'

[fill]
symbol = ' '

[time]
disabled = false
format = '[$time](fg:8)'
time_format = '%v %R'

